spring:
  config:
    import: optional:configserver:http://127.0.0.1:8888/
  cloud:
    config:
      name: api-gateway
  application:
    name: api-gateway
  profiles:
    active: local
    include:
      - jwt
      - eureka
      - actuator
      - routes

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
